import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/admin/app.css',
                'resources/css/admin/design-handoff-admin.css',
                'resources/css/admin/theme-settings.css',
                'resources/css/admin/builder.css',
                'resources/css/admin/builder-homepage.css',
                'resources/css/admin/builder-product-card.css',
                'resources/css/frontend/app.css',
                'resources/css/frontend/design-system-bundle.css',
                'resources/css/frontend/rtl.css',
                'resources/css/frontend/header.css',
                'resources/css/frontend/footer.css',
                'resources/css/frontend/layout.css',
                'resources/css/frontend/mobile.css',
                'resources/css/frontend/pages.css',
                'resources/css/frontend/components.css',
                'resources/css/frontend/product.css',
                'resources/css/frontend/shop.css',
                'resources/js/admin/app.js',
                'resources/js/admin/pos-terminal.js',
                'resources/js/admin/builder/index.js',
                'resources/js/admin/theme-settings.js',
                'resources/js/admin/header-builder.js',
                'resources/js/admin/footer-builder.js',
                'resources/js/admin/homepage-builder.js',
                'resources/js/admin/product-card-builder.js',
                'resources/js/admin/product-page-builder.js',
                'resources/js/admin/shop-builder.js',
                'resources/js/admin/product-form.js',
                'resources/js/admin/menu-builder.js',
                'resources/js/admin/import-export.js',
                'resources/js/admin/analytics.js',
                'resources/js/admin/shipments.js',
                'resources/js/shared/media-picker.js',
                'resources/js/frontend/app.js',
                'resources/js/frontend/sticky-header.js',
                'resources/js/frontend/mobile-menu.js',
                'resources/js/frontend/search.js',
                'resources/js/frontend/mega-menu.js',
                'resources/js/frontend/toast.js',
                'resources/js/frontend/preloader.js',
                'resources/js/frontend/shop-filters.js',
                'resources/js/frontend/variations.js',
                'resources/js/frontend/cart.js',
                'resources/js/frontend/wishlist.js',
                'resources/js/frontend/compare.js',
                'resources/js/frontend/checkout.js',
                'resources/js/frontend/product-page.js',
            ],
            refresh: true,
        }),
    ],
});
