<?php

/**
 * Named admin route => required StaffPermissions key (staff users only; admin bypasses).
 */
return [
    'admin.index' => 'view_dashboard',
    'admin.dashboard' => 'view_dashboard',

    'admin.emails.index' => 'manage_settings',
    'admin.emails.edit' => 'manage_settings',
    'admin.emails.update' => 'manage_settings',
    'admin.emails.test' => 'manage_settings',

    'admin.smtp.index' => 'manage_settings',
    'admin.smtp.save' => 'manage_settings',
    'admin.smtp.test' => 'manage_settings',

    'admin.sms.index' => 'manage_settings',
    'admin.sms.save' => 'manage_settings',
    'admin.sms.test' => 'manage_settings',

    'admin.newsletter.index' => 'send_newsletters',
    'admin.newsletter.create' => 'send_newsletters',
    'admin.newsletter.store' => 'send_newsletters',
    'admin.newsletter.send' => 'send_newsletters',
    'admin.newsletter.retry' => 'send_newsletters',
    'admin.newsletter.cancel' => 'send_newsletters',
    'admin.newsletter.subscribers' => 'send_newsletters',

    'admin.reports.sales' => 'view_reports',
    'admin.reports.products' => 'view_reports',
    'admin.reports.customers' => 'view_reports',
    'admin.reports.earnings' => 'view_reports',

    'admin.analytics.index' => 'view_reports',

    'admin.flash-deals.index' => 'manage_flash_deals',
    'admin.flash-deals.create' => 'manage_flash_deals',
    'admin.flash-deals.store' => 'manage_flash_deals',

    'admin.menus.index' => 'manage_theme',
    'admin.menus.store' => 'manage_theme',
    'admin.menus.items.store' => 'manage_theme',
    'admin.menus.items.update' => 'manage_theme',
    'admin.menus.items.destroy' => 'manage_theme',
    'admin.menus.reorder' => 'manage_theme',

    'admin.products.index' => 'view_products',
    'admin.products.create' => 'create_products',
    'admin.products.store' => 'create_products',
    'admin.products.edit' => 'edit_products',
    'admin.products.update' => 'edit_products',
    'admin.products.destroy' => 'delete_products',
    'admin.products.bulk-action' => 'edit_products',
    'admin.products.bulk-import' => 'edit_products',
    'admin.products.export' => 'view_products',
    'admin.products.generate-sku' => 'edit_products',
    'admin.products.ai-generate' => 'edit_products',

    'admin.categories.index' => 'manage_categories',
    'admin.brands.index' => 'manage_brands',

    'admin.orders.index' => 'view_orders',
    'admin.orders.show' => 'view_orders',
    'admin.orders.status' => 'update_order_status',
    'admin.orders.item-status' => 'update_order_status',
    'admin.orders.invoice' => 'view_invoices',
    'admin.orders.export' => 'export_orders',

    'admin.sellers.index' => 'view_sellers',
    'admin.sellers.show' => 'view_sellers',
    'admin.sellers.approve' => 'approve_sellers',
    'admin.sellers.suspend' => 'suspend_sellers',
    'admin.sellers.followers' => 'view_sellers',

    'admin.customers.index' => 'view_customers',
    'admin.customers.show' => 'view_customers',
    'admin.customers.create' => 'create_customers',
    'admin.customers.store' => 'create_customers',
    'admin.customers.edit' => 'edit_customers',
    'admin.customers.update' => 'edit_customers',
    'admin.customers.toggle-status' => 'edit_customers',
    'admin.customers.wallet' => 'edit_customers',
    'admin.customers.points' => 'edit_customers',
    'admin.customers.login-as' => 'edit_customers',
    'admin.customers.export' => 'view_customers',

    'admin.coupons.index' => 'manage_coupons',
    'admin.coupons.create' => 'manage_coupons',
    'admin.coupons.store' => 'manage_coupons',
    'admin.coupons.edit' => 'manage_coupons',
    'admin.coupons.update' => 'manage_coupons',
    'admin.coupons.toggle' => 'manage_coupons',
    'admin.coupons.stats' => 'manage_coupons',
    'admin.coupons.import-template' => 'manage_coupons',
    'admin.coupons.generate-code' => 'manage_coupons',
    'admin.coupons.bulk-generate' => 'manage_coupons',
    'admin.coupons.import' => 'manage_coupons',
    'admin.coupons.destroy' => 'manage_coupons',

    'admin.shipping.index' => 'view_shipping',
    'admin.shipping.method' => 'manage_shipping',
    'admin.shipping.method.save' => 'manage_shipping',
    'admin.shipping.areas' => 'manage_shipping',
    'admin.shipping.carriers' => 'manage_shipping',

    'admin.payment.index' => 'view_payments',
    'admin.payments.update' => 'manage_payments',

    'admin.withdrawals.index' => 'manage_withdrawals',
    'admin.withdrawals.process' => 'manage_withdrawals',
    'admin.withdrawals.reject' => 'manage_withdrawals',

    'admin.commission.index' => 'view_seller_earnings',
    'admin.commission.save' => 'view_seller_earnings',

    'admin.settings.index' => 'view_settings',
    'admin.settings.general' => 'manage_settings',
    'admin.settings.general.save' => 'manage_settings',
    'admin.settings.business' => 'manage_settings',
    'admin.settings.business.save' => 'manage_settings',
    'admin.settings.smtp' => 'manage_settings',
    'admin.settings.smtp.save' => 'manage_settings',
    'admin.settings.smtp.test' => 'manage_settings',
    'admin.settings.social-login' => 'manage_settings',
    'admin.settings.social-login.save' => 'manage_settings',
    'admin.settings.seo' => 'manage_settings',
    'admin.settings.seo.save' => 'manage_settings',
    'admin.settings.license' => 'manage_settings',
    'admin.settings.license.reactivate' => 'manage_settings',
    'admin.settings.reviews' => 'manage_settings',
    'admin.settings.reviews.save' => 'manage_settings',
    'admin.settings.points' => 'manage_settings',
    'admin.settings.points.save' => 'manage_settings',

    'admin.settings.system' => 'manage_settings',
    'admin.settings.system.save' => 'manage_settings',
    'admin.settings.order' => 'manage_settings',
    'admin.settings.order.save' => 'manage_settings',
    'admin.settings.tax' => 'manage_settings',
    'admin.settings.tax.save' => 'manage_settings',
    'admin.settings.customer' => 'manage_settings',
    'admin.settings.customer.save' => 'manage_settings',
    'admin.settings.seller' => 'manage_settings',
    'admin.settings.seller.save' => 'manage_settings',
    'admin.settings.units' => 'manage_settings',
    'admin.settings.units.save' => 'manage_settings',
    'admin.settings.cookie' => 'manage_settings',
    'admin.settings.cookie.save' => 'manage_settings',
    'admin.settings.maintenance' => 'manage_settings',
    'admin.settings.maintenance.save' => 'manage_settings',
    'admin.settings.backup' => 'manage_settings',
    'admin.settings.backup.save' => 'manage_settings',
    'admin.settings.backup.run' => 'manage_settings',

    'admin.theme-settings' => 'manage_theme',
    'admin.theme-settings.save' => 'manage_theme',
    'admin.theme-settings.reset' => 'manage_theme',
    'admin.theme-settings.export' => 'manage_theme',
    'admin.theme-settings.import' => 'manage_theme',

    'admin.builder.index' => 'manage_theme',
    'admin.builder.header' => 'manage_theme',
    'admin.builder.footer' => 'manage_theme',
    'admin.builder.homepage' => 'manage_theme',
    'admin.builder.product-card' => 'manage_theme',
    'admin.builder.product-page' => 'manage_theme',
    'admin.builder.shop' => 'manage_theme',

    'admin.addons.index' => 'manage_settings',
    'admin.addons.install' => 'manage_settings',
    'admin.addons.upload-install' => 'manage_settings',
    'admin.addons.activate' => 'manage_settings',
    'admin.addons.deactivate' => 'manage_settings',
    'admin.addons.uninstall' => 'manage_settings',
    'admin.addons.settings' => 'manage_settings',

    'admin.reviews.index' => 'view_reviews',
    'admin.reviews.approve' => 'approve_reviews',
    'admin.reviews.reject' => 'approve_reviews',
    'admin.reviews.bulk' => 'approve_reviews',
    'admin.reviews.reply' => 'reply_reviews',
    'admin.reviews.custom' => 'approve_reviews',
    'admin.reviews.destroy' => 'delete_reviews',

    'admin.qna.index' => 'manage_qna',
    'admin.qna.questions.approve' => 'manage_qna',
    'admin.qna.questions.reject' => 'manage_qna',
    'admin.qna.answers.approve' => 'manage_qna',
    'admin.qna.questions.destroy' => 'manage_qna',
    'admin.qna.answers.destroy' => 'manage_qna',
    'admin.qna.admin-answer' => 'manage_qna',

    'admin.update.index' => 'manage_settings',
    'admin.update.check' => 'manage_settings',
    'admin.update.download' => 'manage_settings',
    'admin.update.apply' => 'manage_settings',
    'admin.update.upload' => 'manage_settings',

    'admin.staff.index' => 'manage_staff',
    'admin.staff.create' => 'manage_staff',
    'admin.staff.store' => 'manage_staff',
    'admin.staff.edit' => 'manage_staff',
    'admin.staff.update' => 'manage_staff',
    'admin.staff.toggle-status' => 'manage_staff',
    'admin.staff.destroy' => 'manage_staff',
    'admin.staff.activity' => 'manage_staff',

    'admin.features.index' => 'manage_settings',
    'admin.features.save' => 'manage_settings',

    'admin.pages.index' => 'manage_settings',
    'admin.pages.create' => 'manage_settings',
    'admin.pages.store' => 'manage_settings',
    'admin.pages.edit' => 'manage_settings',
    'admin.pages.update' => 'manage_settings',
    'admin.pages.destroy' => 'manage_settings',
    'admin.pages.reorder' => 'manage_settings',

    'admin.faq.index' => 'manage_settings',
    'admin.faq.store' => 'manage_settings',
    'admin.faq.update' => 'manage_settings',
    'admin.faq.destroy' => 'manage_settings',
    'admin.faq.reorder' => 'manage_settings',

    'admin.contact.index' => 'manage_settings',
    'admin.contact.show' => 'manage_settings',
    'admin.contact.reply' => 'manage_settings',

    'admin.import-export.products' => 'view_products',
    'admin.import-export.products.import' => 'edit_products',
    'admin.import-export.products.status' => 'view_products',
    'admin.import-export.products.template' => 'view_products',
    'admin.import-export.products.export' => 'view_products',
    'admin.import-export.orders.export' => 'export_orders',
    'admin.import-export.customers.export' => 'view_customers',

    'admin.translations.index' => 'manage_settings',
    'admin.translations.ui' => 'manage_settings',
    'admin.translations.ui.save' => 'manage_settings',
    'admin.translations.ui.auto' => 'manage_settings',
    'admin.translations.ui.export' => 'manage_settings',
    'admin.translations.ui.import' => 'manage_settings',
];
