export function getExtendedBlocks() {
  return [
    {
      id: 'widget-product-slider',
      label: 'Product Slider',
      category: '🛍️ eCommerce',
      media: '<div style="font-size:28px;text-align:center">🎠</div>',
      content: { type: 'ec-product-slider' },
    },
    {
      id: 'widget-single-product',
      label: 'Featured Product',
      category: '🛍️ eCommerce',
      media: '<div style="font-size:28px;text-align:center">⭐</div>',
      content: { type: 'ec-single-product' },
    },
    {
      id: 'widget-flash-sale',
      label: 'Flash Sale Timer',
      category: '🛍️ eCommerce',
      media: '<div style="font-size:28px;text-align:center">⚡</div>',
      content: { type: 'ec-flash-sale' },
    },
    {
      id: 'widget-brand-carousel',
      label: 'Brand Logos',
      category: '🛍️ eCommerce',
      media: '<div style="font-size:28px;text-align:center">🏷️</div>',
      content: { type: 'ec-brands' },
    },
    {
      id: 'widget-testimonial-slider',
      label: 'Review Slider',
      category: '📣 Marketing',
      media: '<div style="font-size:28px;text-align:center">💬</div>',
      content: `<div class="testimonial-slider-widget" style="padding:48px 0;background:#f8fafc"><div style="text-align:center;margin-bottom:32px"><h2 style="font-size:30px;font-weight:700;color:#1e293b">What Customers Say</h2></div><div style="display:flex;gap:20px;overflow:hidden;max-width:1000px;margin:0 auto;padding:0 20px">${[1,2,3].map(() => `<div style="flex:0 0 calc(33.333% - 14px);background:white;border-radius:16px;padding:28px;box-shadow:0 2px 12px rgba(0,0,0,0.06)"><div style="color:#fbbf24;font-size:18px;margin-bottom:12px">★★★★★</div><p style="color:#475569;line-height:1.7;font-style:italic;margin-bottom:16px">"Excellent product quality and fast delivery. Will definitely order again!"</p><div style="display:flex;align-items:center;gap:10px"><div style="width:40px;height:40px;border-radius:50%;background:#2563eb;color:white;display:flex;align-items:center;justify-content:center;font-weight:700">C</div><div><div style="font-weight:600;color:#1e293b;font-size:14px">Customer Name</div><div style="font-size:12px;color:#94a3b8">Verified Buyer</div></div></div></div>`).join('')}</div></div>`,
    },
    {
      id: 'widget-icon-box',
      label: 'Icon Box',
      category: '📣 Marketing',
      media: '<div style="font-size:28px;text-align:center">📦</div>',
      content: `<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:24px;padding:40px 0">${['🚚 Free Shipping|On orders over $50','🔒 Secure Payment|100% Protected','🔄 Easy Returns|30-day policy','📞 24/7 Support|Always here'].map((item) => { const [icon, desc] = item.split('|'); const parts = icon.split(' '); const emoji = parts[0]; const title = parts.slice(1).join(' '); return `<div style="text-align:center;padding:28px 20px;background:white;border-radius:12px;border:1px solid #e2e8f0"><div style="font-size:40px;margin-bottom:12px">${emoji}</div><h4 style="font-size:16px;font-weight:700;color:#1e293b;margin-bottom:6px">${title}</h4><p style="font-size:13px;color:#64748b">${desc}</p></div>`; }).join('')}</div>`,
    },
    {
      id: 'widget-pricing-table',
      label: 'Pricing Table',
      category: '📣 Marketing',
      media: '<div style="font-size:28px;text-align:center">💰</div>',
      content: `<div style="padding:48px 0"><h2 style="text-align:center;font-size:32px;font-weight:700;color:#1e293b;margin-bottom:32px">Choose Your Plan</h2><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:20px;max-width:900px;margin:0 auto">${[{name:'Basic',price:'$9',color:'#64748b',features:['10 Products','1GB Storage','Email Support']},{name:'Pro',price:'$29',color:'#2563eb',features:['100 Products','10GB Storage','Priority Support','Analytics']},{name:'Enterprise',price:'$79',color:'#7c3aed',features:['Unlimited','100GB Storage','24/7 Support','Custom Domain','API Access']}].map((plan, i) => `<div style="background:white;border-radius:16px;padding:28px;border:2px solid ${i===1 ? plan.color : '#e2e8f0'};${i===1 ? 'transform:scale(1.05)' : ''}"><div style="font-size:16px;font-weight:700;color:${plan.color};margin-bottom:8px">${plan.name}</div><div style="font-size:42px;font-weight:800;color:#1e293b;margin-bottom:20px">${plan.price}<span style="font-size:14px;font-weight:400;color:#94a3b8">/month</span></div><ul style="list-style:none;margin-bottom:24px">${plan.features.map((f) => `<li style="padding:6px 0;font-size:14px;color:#475569;border-bottom:1px solid #f1f5f9">✓ ${f}</li>`).join('')}</ul><a href="#" style="display:block;text-align:center;padding:12px;background:${i===1 ? plan.color : 'transparent'};color:${i===1 ? 'white' : plan.color};border:2px solid ${plan.color};border-radius:8px;font-weight:600;text-decoration:none;font-size:14px">Get Started</a></div>`).join('')}</div></div>`,
    },
    {
      id: 'widget-before-after',
      label: 'Before / After',
      category: '🖼️ Media',
      media: '<div style="font-size:28px;text-align:center">↔️</div>',
      content: `<div class="before-after-widget" style="position:relative;overflow:hidden;border-radius:12px;max-width:700px;margin:0 auto;aspect-ratio:16/9;background:#e2e8f0"><div style="position:absolute;inset:0"><img src="https://placehold.co/700x400/e2e8f0/94a3b8?text=Before" style="width:100%;height:100%;object-fit:cover" alt="Before"></div><div style="position:absolute;inset:0;clip-path:inset(0 50% 0 0)"><img src="https://placehold.co/700x400/2563eb/ffffff?text=After" style="width:100%;height:100%;object-fit:cover" alt="After"></div></div>`,
    },
    {
      id: 'widget-tabs',
      label: 'Tabs',
      category: '📐 Layout',
      media: '<div style="font-size:28px;text-align:center">📑</div>',
      content: `<div style="border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="display:flex;background:#f8fafc;border-bottom:1px solid #e2e8f0"><button style="padding:14px 24px;border:none;background:white;color:#2563eb;border-bottom:2px solid #2563eb">Tab One</button><button style="padding:14px 24px;border:none;background:transparent;color:#64748b">Tab Two</button><button style="padding:14px 24px;border:none;background:transparent;color:#64748b">Tab Three</button></div><div style="padding:24px"><h3 style="font-size:18px;font-weight:600;color:#1e293b;margin-bottom:10px">Tab Content</h3><p style="color:#64748b;line-height:1.7">Add your content here. Switch logic can be implemented on frontend.</p></div></div>`,
    },
    {
      id: 'widget-accordion',
      label: 'Accordion / FAQ',
      category: '📐 Layout',
      media: '<div style="font-size:28px;text-align:center">📋</div>',
      content: `<div style="border:1px solid #e2e8f0;border-radius:12px;overflow:hidden">${['What is your return policy?','How long does shipping take?','Do you offer international shipping?','How can I track my order?'].map((q) => `<div style="border-bottom:1px solid #e2e8f0"><div style="padding:16px 20px;font-size:15px;font-weight:500;color:#1e293b;display:flex;justify-content:space-between"><span>${q}</span><span style="color:#2563eb">+</span></div></div>`).join('')}</div>`,
    },
    {
      id: 'widget-countdown',
      label: 'Countdown Timer',
      category: '📣 Marketing',
      media: '<div style="font-size:28px;text-align:center">⏰</div>',
      content: `<div style="background:linear-gradient(135deg,#ef4444,#dc2626);color:white;padding:40px;text-align:center;border-radius:16px"><div style="font-size:14px;font-weight:600;text-transform:uppercase;letter-spacing:0.1em;opacity:0.85;margin-bottom:8px">Limited Time Offer Ends In</div><div style="display:flex;justify-content:center;gap:16px;margin-bottom:24px">${['Days','Hours','Mins','Secs'].map((unit) => `<div><div style="background:rgba(0,0,0,0.2);border-radius:12px;padding:16px 20px;min-width:70px"><div style="font-size:42px;font-weight:800;line-height:1">00</div></div><div style="font-size:11px;opacity:0.7;margin-top:6px;text-transform:uppercase">${unit}</div></div>`).join('')}</div><a href="/shop" style="display:inline-block;background:white;color:#ef4444;padding:14px 36px;border-radius:30px;font-weight:700;font-size:16px;text-decoration:none">Shop the Sale →</a></div>`,
    },
    {
      id: 'widget-size-guide',
      label: 'Size Guide',
      category: '🛍️ eCommerce',
      media: '<div style="font-size:28px;text-align:center">📏</div>',
      content: `<div style="border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="padding:16px 20px;background:#f8fafc;border-bottom:1px solid #e2e8f0"><h3 style="font-size:16px;font-weight:700;color:#1e293b;margin:0">📏 Size Guide</h3></div><div style="overflow-x:auto;padding:16px"><table style="width:100%;border-collapse:collapse;font-size:14px"><thead><tr style="background:#f8fafc">${['Size','XS','S','M','L','XL','XXL'].map((h)=>`<th style="padding:10px;text-align:center;font-weight:600;color:#64748b;border-bottom:2px solid #e2e8f0">${h}</th>`).join('')}</tr></thead><tbody>${[['Chest (cm)','80','88','96','104','112','120'],['Waist (cm)','64','72','80','88','96','104'],['Hip (cm)','88','96','104','112','120','128']].map((row)=>`<tr style="border-bottom:1px solid #f1f5f9">${row.map((cell,i)=>`<td style="padding:10px;text-align:center;font-weight:${i===0?'600':'400'};color:${i===0?'#1e293b':'#475569'}">${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`,
    },
    {
      id: 'widget-contact-form',
      label: 'Contact Form',
      category: '📣 Marketing',
      media: '<div style="font-size:28px;text-align:center">📨</div>',
      content: `<div style="background:white;border:1px solid #e2e8f0;border-radius:16px;padding:32px;max-width:600px;margin:0 auto"><h3 style="font-size:24px;font-weight:700;color:#1e293b;margin-bottom:24px">Get In Touch</h3><form action="/contact" method="POST" style="display:flex;flex-direction:column;gap:16px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><div><label style="display:block;font-size:13px;font-weight:500;color:#374151;margin-bottom:6px">Your Name *</label><input type="text" name="name" required style="width:100%;padding:10px 12px;border:1px solid #d1d5db;border-radius:8px;font-size:14px;outline:none"></div><div><label style="display:block;font-size:13px;font-weight:500;color:#374151;margin-bottom:6px">Email *</label><input type="email" name="email" required style="width:100%;padding:10px 12px;border:1px solid #d1d5db;border-radius:8px;font-size:14px;outline:none"></div></div><div><label style="display:block;font-size:13px;font-weight:500;color:#374151;margin-bottom:6px">Subject *</label><input type="text" name="subject" required style="width:100%;padding:10px 12px;border:1px solid #d1d5db;border-radius:8px;font-size:14px;outline:none"></div><div><label style="display:block;font-size:13px;font-weight:500;color:#374151;margin-bottom:6px">Message *</label><textarea name="message" rows="4" required style="width:100%;padding:10px 12px;border:1px solid #d1d5db;border-radius:8px;font-size:14px;outline:none;resize:vertical"></textarea></div><button type="submit" style="padding:12px 32px;background:#2563eb;color:white;border:none;border-radius:8px;font-size:15px;font-weight:600;cursor:pointer;align-self:flex-start">Send Message →</button></form></div>`,
    },
    {
      id: 'widget-map',
      label: 'Google Map',
      category: '📐 Layout',
      media: '<div style="font-size:28px;text-align:center">🗺️</div>',
      content: `<div style="border-radius:12px;overflow:hidden;height:400px"><iframe src="https://www.google.com/maps?q=Dhaka&z=12&output=embed" width="100%" height="100%" style="border:0" loading="lazy"></iframe></div>`,
    },
    {
      id: 'widget-instagram',
      label: 'Instagram Feed',
      category: '📣 Marketing',
      media: '<div style="font-size:28px;text-align:center">📸</div>',
      content: `<div style="padding:40px 0"><div style="text-align:center;margin-bottom:24px"><h3 style="font-size:24px;font-weight:700;color:#1e293b;margin-bottom:4px">Follow Us on Instagram</h3><a href="#" style="color:#e1306c;font-size:14px;font-weight:500">@yourhandle</a></div><div style="display:grid;grid-template-columns:repeat(6,1fr);gap:4px">${Array(6).fill(0).map(() => `<div style="aspect-ratio:1;background:#f1f5f9;border-radius:4px;overflow:hidden"><img src="https://placehold.co/200x200/e2e8f0/94a3b8?text=📸" style="width:100%;height:100%;object-fit:cover"></div>`).join('')}</div></div>`,
    },
    {
      id: 'widget-team',
      label: 'Team Members',
      category: '📣 Marketing',
      media: '<div style="font-size:28px;text-align:center">👥</div>',
      content: `<div style="padding:48px 0"><h2 style="text-align:center;font-size:32px;font-weight:700;color:#1e293b;margin-bottom:40px">Meet Our Team</h2><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:24px">${['Alice Johnson','Bob Smith','Carol Davis','Dan Wilson'].map((name, i) => `<div style="text-align:center"><div style="width:100px;height:100px;border-radius:50%;background:${['#2563eb','#10b981','#f59e0b','#8b5cf6'][i]};margin:0 auto 16px;display:flex;align-items:center;justify-content:center;font-size:36px;color:white;font-weight:700">${name[0]}</div><h4 style="font-size:16px;font-weight:700;color:#1e293b;margin-bottom:4px">${name}</h4><p style="font-size:13px;color:#64748b;margin-bottom:12px">Team Member</p></div>`).join('')}</div></div>`,
    },
  ];
}
